DROP TABLE IF EXISTS libro;
DROP TABLE IF EXISTS autor;

CREATE TABLE autor (id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(150), apellido VARCHAR(150));

CREATE TABLE libro (id INT PRIMARY KEY AUTO_INCREMENT, titulo VARCHAR(250), resumen VARCHAR(2000), url VARCHAR(500), autor_id INT NOT NULL);
ALTER TABLE libro ADD FOREIGN KEY (autor_id) REFERENCES autor(id);

INSERT INTO autor(id, nombre, apellido)
VALUES 
(1, 'Augusto','Monterroso'),
(2, 'Mario','Benedetti'),
(3, 'Andres','Caicedo'),
(4, 'Charles','Bukowski');

INSERT INTO libro (titulo, resumen, url, autor_id)
VALUES 
('Obras Completas (Y Otros Cuentos)', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 1),
('Movimiento Perpetuo', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 1),
('La Palabra Magica', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 1),
('La Oveja Negra Y Demas Fabulas', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 1),
('Lo Demas Es Silencio', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 1),
('Esta Mañana', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Montivideanos', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('La Muerte Y Otras Sorpresas', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Con Y Sin Nostalgia', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Geografias', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Despistes Y Franquezas', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Buzon De Tiempo', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('El Porvenir De Mi Pasado', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 2),
('Calicalabozo', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 3),
('Angelitos Empantanados', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 3),
('El Atravesado', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 3),
('Narraciones Tempranas', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 3),
('Escritos De Un Viejo Indecente', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 4),
('La Maquina De Follar', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 4),
('Erecciones, Eyaculaciones, Exhibiciones', 'Lorem ipsum dolor sit amet. Est internos dolor ut voluptas praesentium ab consequatur odit in vitae quisquam est nihil molestiae ad sint facilis? Qui quasi autem et recusandae magni aut deleniti dolores et autem esse id nihil pariatur. Aut quod nihil est voluptates excepturi aut maxime modi et laboriosam molestiae?', 'https://emvinc.wpenginepowered.com/wp-content/uploads/2015/05/not-available.png', 4);
